"use server";
import { db } from "@/lib/db";
import { requireAgent,ensureExercise } from "@/lib/data";
import { put } from "@vercel/blob";
import { revalidatePath } from "next/cache";
export async function scanEan(form:FormData){const a=await requireAgent(),location=String(form.get("location")||""),ean=String(form.get("ean")||"").trim().replace(/\s/g,"");if(!location||!ean)return {error:"Scannez un EAN valide."};const ex=await ensureExercise(a.depotId,a.userId);const loc=await db.query("select l.id from locations l join aisles s on s.id=l.aisle_id where l.id=$1 and s.depot_id=$2 and s.active",[location,a.depotId]);if(!loc.rowCount)return {error:"Emplacement invalide."};const found=await db.query("select id,article_code,designation from articles where depot_id=$1 and ean=$2",[a.depotId,ean]);const result=await db.query("insert into presences(exercise_id,location_id,agent_id,ean,article_id) values($1,$2,$3,$4,$5) on conflict(exercise_id,location_id,ean) do nothing returning id",[ex,location,a.userId,ean,found.rows[0]?.id||null]);if(!result.rowCount){const old=await db.query("select id from presences where exercise_id=$1 and location_id=$2 and ean=$3",[ex,location,ean]);return {duplicate:true,id:old.rows[0].id,ean,known:!!found.rowCount,article:found.rows[0]||null}}revalidatePath("/comptage");return {id:result.rows[0].id,ean,known:!!found.rowCount,article:found.rows[0]||null}}
export async function getLocationScans(location:string){const a=await requireAgent(),ex=await ensureExercise(a.depotId,a.userId);const check=await db.query("select 1 from locations l join aisles s on s.id=l.aisle_id where l.id=$1 and s.depot_id=$2",[location,a.depotId]);if(!check.rowCount)return [];const r=await db.query("select p.id,p.ean,ar.article_code,ar.designation,ar.id is not null as known,lp.url as photo from presences p left join articles ar on ar.id=p.article_id left join lateral(select url from label_photos where presence_id=p.id order by created_at desc limit 1) lp on true where p.exercise_id=$1 and p.location_id=$2 order by p.scanned_at desc",[ex,location]);return r.rows.map(x=>({id:x.id,ean:x.ean,known:x.known,article:x.known?{article_code:x.article_code,designation:x.designation}:null,photo:x.photo||undefined}))}
export async function savePhoto(form:FormData){const a=await requireAgent();const presence=String(form.get("presence")||""),file=form.get("photo");if(!presence||!(file instanceof File)||!file.size)return {error:"Photo manquante."};if(file.size>4*1024*1024)return {error:"Erreur : la photo dépasse 4 Mo."};const check=await db.query("select p.id from presences p join exercises e on e.id=p.exercise_id where p.id=$1 and e.depot_id=$2 and p.article_id is null",[presence,a.depotId]);if(!check.rowCount)return {error:"Relevé photo invalide."};if(!process.env.BLOB_READ_WRITE_TOKEN)return {error:"Configurez BLOB_READ_WRITE_TOKEN pour activer les photos."};const blob=await put(`etiquettes/${a.depotId}/${presence}-${Date.now()}.jpg`,file,{access:"public",addRandomSuffix:false});await db.query("insert into label_photos(presence_id,url) values($1,$2)",[presence,blob.url]);revalidatePath("/comptage");return {url:blob.url}}
export async function validateLocation(form:FormData){const a=await requireAgent(),location=String(form.get("location")||"");const ex=await ensureExercise(a.depotId,a.userId);const r=await db.query("select l.id,l.code,l.seq,s.id aisle_id,s.code aisle_code from locations l join aisles s on s.id=l.aisle_id where l.id=$1 and s.depot_id=$2",[location,a.depotId]);if(!r.rowCount)return {error:"Emplacement invalide."};const current=r.rows[0];const missing=await db.query("select p.ean from presences p where p.exercise_id=$1 and p.location_id=$2 and p.article_id is null and not exists(select 1 from label_photos lp where lp.presence_id=p.id)",[ex,location]);if(missing.rowCount)return {error:`Photo d’étiquette obligatoire pour l’EAN ${missing.rows[0].ean}.`};await db.query("insert into validated_locations(exercise_id,location_id,agent_id) values($1,$2,$3) on conflict(exercise_id,location_id) do nothing",[ex,location,a.userId]);const next=await db.query("select id,code from locations where aisle_id=$1 and seq>$2 order by seq limit 1",[current.aisle_id,current.seq]);revalidatePath("/comptage");return {next:next.rows[0]||null,aisle:current.aisle_code}}
